# .pages.yml

# Media configuration
media:
  input: public/images
  output: /images

# Content collections
content:
  # Homepage content (if you have homepage content collection)
  - name: homepage
    label: Homepage
    type: collection
    path: src/content/homepage
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
      - name: body
        label: Body Content
        type: rich-text

  # If you have other collections, add them here
  # For example, if you have a blog or services collection:
  # - name: blog
  #   label: Blog Posts
  #   type: collection
  #   path: src/content/blog
  #   extension: md
  #   fields:
  #     - name: title
  #       label: Title
  #       type: string
  #       required: true
  #     - name: pubDate
  #       label: Publish Date
  #       type: date
  #     - name: description
  #       label: Description
  #       type: text
  #     - name: heroImage
  #       label: Hero Image
  #       type: image
  #     - name: body
  #       label: Content
  #       type: rich-text